### ISSUE TITLE
UOW and cyclic dependencies

### ISSUE THREAD

**Issue by sethstone** [financialforcedev/fflib-apex-common#1]
The UOW pattern currently doesn't support cyclic dependencies as stated in:
http://andyinthecloud.com/2013/06/09/managing-your-dml-and-transactions-with-a-unit-of-work/

> _Note: If you have some cyclic dependencies in your schema, you will have to either use two separate unit of work instances or simply handle this directly using DML._

If this could be handled generically in the UOW logic it could be very useful in certain situations.  I also agree with Tom Gagne that it may be best to re-factor your data model to avoid this situation altogether, but if it's needed having UOW handle it would be ideal.

**Comment by afawcett** [comment]
@agarciaffdc another that has been merged and can now be closed! 👍
