### ISSUE TITLE
addOrdering is not defining the sort order

### ISSUE THREAD

**Issue by o-lexi** [financialforcedev/fflib-apex-common#102]
When I add
`addOrdering(Account.LastModifiedDate, fflib_QueryFactory.SortOrder.DESCENDING).` into `newQueryFactory()`, the records are returned sorted by name (aka default sort).
When I use `[SELECT Id, Name FROM Account ORDER BY LastModifiedDate DESC]` in the Selector, it gets sorted correctly.
Also when I override getOrderBy with 
`public override String getOrderBy() {return 'LastModifiedDate DESC';}` the records get sorted accordingly and it looks like any addOrdering commands sorting is performed before this 'final' sorting.

P.S. I was able to have addOrdering taken into the consideration when I was using in getOrderBy the field that has all null or same values, so the sort order done by addOrdering is not get resorted.

**Comment by afawcett** [comment]
Are you able to demonstrate this in the form of a test method?

**Comment by afawcett** [comment]
@o-lexi I'm keen to progress this issue, but need a bit more information from you to better understand if its a bug or enhancement your raising here.

**Comment by afawcett** [comment]
@o-lexi ping us back here if you still want to discuss.

**Comment by rsoesemann** [comment]
@afawcett Just stumbled over this. I think it was connected to https://github.com/financialforcedev/fflib-apex-common/issues/102. Name was the default and we used nomatter what addOrdering() added.
