### ISSUE TITLE
Where to place logic, Domain vs Service?

### ISSUE THREAD

**Issue by afawcett** [financialforcedev/fflib-apex-common#109]
Started this post to gather feedback on some content i'm writing to help with the common question of 'Where to place my logic, Domain or Service' 

**Business Logic in the Domain class vs Service class?**
Sometimes it can feel less than obvious where to place code. Lets go back to the **Separation of Concerns** principle and think about what the Service and Domain layers are concerned with. 

<img width="763" alt="screen shot 2016-02-26 at 18 56 18" src="https://cloud.githubusercontent.com/assets/1167760/13362174/add137f2-dcba-11e5-9752-8f16a4c8c8df.png">

**Comment by afawcett** [comment]
Fowlers definitions...

Service Layer, “_Defines an application's boundary with a layer of services that establishes a set of available operations and coordinates the application's response in each operation._” Martin Fowler / Randy Stafford, EAA Patterns

Domain Model, “_An object model of the domain that incorporates both behavior and data.”, “At its worst business logic can be very complex. Rules and logic describe many different cases and slants of behavior, and it's this complexity that objects were designed to work with..._” Martin Fowler, EAA Patterns

**Comment by afawcett** [comment]
I'd like a few views on the concerns i've listed above as well as other concerns we could list to help people understand where placement goes. I suspect sometimes just having some tightly written code in the service layer could be a preference at times to breaking things out into domain layer calcs or updates?

**Comment by jmrjulian** [comment]
I have challenges with 3 and 4 around the suggestion of implementing cross-object behaviour at the Domain layer, especially when they are invoked by triggers.

At worst, such a design could inadvertently cause a chain reaction of triggers which results to a variety of problems (e.g. SOQL limits, CPU time limit, trigger recursions, etc) that are particularly difficult to troubleshoot and unwind without regression. It does not scale well in an enterprise-level application that is developed iteratively.

Refactoring the design typically involves implementing the behaviour back to Service layer which in SFDC also implies sacrificing SFDC's standard forms (new/edit pages) with custom controller or controller extensions.

**Comment by afawcett** [comment]
Great feedback @jmrjulian thank you, will give this some thought!

**Comment by mustafaturabali** [comment]
@afawcett I am building a complex subscription management system in which bulk of the business logic is invoked through triggers. There are certain scenarios where I don't want subsequent triggers to fire (stop recursion as well as chaining of triggers). Can you please provide me some guidance on that? I don't want all trigger methods to stop but want to control which ones should be skipped. Can we build something in fflib_SObjectDomain class for this?

**Comment by mustafaturabali** [comment]
@afawcett also it would be great if we can build some control through custom settings so admins can turn on/off triggers when they want to perform certain operations like data load without invoking triggers.

**Comment by Autobat** [comment]
I think this is what you're looking for :)

https://andyinthecloud.com/2016/04/13/disabling-trigger-events-in-apex-enterprise-patterns/

Chris Mail

**Comment by afawcett** [comment]
@mustafaturabali does at @Autobat's answer help?

(thanks btw @Autobat )

**Comment by afawcett** [comment]
I'll close this issue for now, its bene open since Feb and really was just a feedback call out. Folks can still add to this issue even though its closed.
