### ISSUE TITLE
SObjectDomainTest Failure

### ISSUE THREAD

**Issue by jdcrensh** [financialforcedev/fflib-apex-common#113]
Just pulled in the latest Domain classes with the event toggle changes. I'm getting a test failure in `fflib_SObjectDomainTest.testDisableTriggerEventsBehaviour` line 265:

> STACK TRACE 
> Class.fflib_SObjectDomainTest.testDisableTriggerEventsBehaviour: line 265, column 1
> 
>  MESSAGE 
> System.AssertException: Assertion Failed: Error - Trigger events have been fired when they are disabled: Expected: false, Actual: true

**Comment by Autobat** [comment]
Interesting.  I will build a dev org this morning and test.

Just incase it's important, what type of org are you in?

Chris Mail

**Comment by Autobat** [comment]
Replicated.  Will fix this morning before work.

**Comment by Autobat** [comment]
OK it looks like we have a conflict with another change as the test passes in my branch.  I will pull the latest changes over, figure it out and create a pull request.

Sorry guys,

Chris

**Comment by Autobat** [comment]
Latest update:

Issue is being caused by a null pointer when using the sub-classes to drive the test harness (fflib_SObjectDomain.TestSObjectDisableBehaviourConstructor.class).  This I saw when I first wrote the code and fixed so it is a different problem.  I am still trying to figure out what exactly is causing the null pointer.

**Comment by Autobat** [comment]
have found it.  There is code missing from my commit - i need to head home and get onto my dev machine to commit it and create a pull request.  Should be able to leave work early and get it done in a few hours.

**Comment by jdcrensh** [comment]
Thanks @Autobat!

**Comment by jdcrensh** [comment]
Fix verified
