### ISSUE TITLE
Test Failing - fflib_QueryFactoryTest::addChildQueries_invalidChildRelationship

### ISSUE THREAD

**Issue by arangari** [financialforcedev/fflib-apex-common#116]
While I am debugging the cause of this, I would like to know if someone has faced the same issue?
I have latest commit '748caa4c091edc9cebf320bf5ee4a5c8aa29d2b9'

if package.xml is modified to have version as '36.0' instead of '31.0', then above test fails.
the fix in test is as below diff snippate.

I am not sending this as pull request as I am not sure if library wants to upgrade on version 36.0. 

diff --git a/fflib/src/classes/fflib_QueryFactoryTest.cls b/fflib/src/classes/fflib_QueryFactoryTest.cls
index 4f21576..8daf17b 100644
--- a/fflib/src/classes/fflib_QueryFactoryTest.cls
+++ b/fflib/src/classes/fflib_QueryFactoryTest.cls
@@ -503,7 +503,7 @@ private class fflib_QueryFactoryTest {
                Schema.DescribeSObjectResult descResult = Account.SObjectType.getDescribe();
         Exception e;
                try {
-                       fflib_QueryFactory childQf = qf.subselectQuery(Contact.SObjectType);
-                       fflib_QueryFactory childQf = qf.subselectQuery('Contact');
                      childQf.selectField('Id');
              } catch (fflib_QueryFactory.InvalidSubqueryRelationshipException ex) {
                      e = ex;

**Comment by arangari** [comment]
closing as this was just for information

**Comment by afawcett** [comment]
FYI @frup42

**Comment by frup42** [comment]
As of API v34, the global describe map keys used the fully qualified names of objects, rather than the local names (e.g. MyNameSpace__MyObject__c rather than MyObject__c). So mixing and matching API versions across classes isn't advisable.
I've just run all unit tests with Apexlib classes all on v31 and all on v36. The full suite passed in both cases (apart from an ApexMocks test which expected different `instanceof null` behaviour, but that's another matter).
Closing as I don't think there's anything we need to do here.

**Comment by up2go-rsoesemann** [comment]
I still experience this without having actively changed anything. The package.xml might have been updated by an upload or my IDE. I suggest you just adjust the versions in the library.

**Comment by afawcett** [comment]
@up2go-rsoesemann agree, about time we increased the API version, changing this to an enhancement. THanks.

**Comment by up2go-rsoesemann** [comment]
Any quickfix here so I don't have to comment out this test?

@frup42 @afawcett

**Comment by afawcett** [comment]
@up2go-rsoesemann firstly, happy new year! 👍 

Secondly, i see that the Travis build for this repo is passing, so it looks like the latest code is ok. So i'm confused. Are you getting this on the latest code?

**Comment by frup42** [comment]
I think @up2go-rsoesemann 's pull request #151 fixes this - looking for null objectType rather than 'Contact,' so no namespace worries. Please reopen if you're still getting this on the latest commit!
