### ISSUE TITLE
Query : Is there coverage % captured for this library?

### ISSUE THREAD

**Issue by arangari** [financialforcedev/fflib-apex-common#117]
we are planning to use this library in our development. However i have not found the coverage numbers. 

we would need to add task if number is ~75 vs higher and need to estimate time for the same.

**Comment by jdcrensh** [comment]
I'm certain its overall coverage is above 75%, but I don't have the exact measurement. You could always deploy the library to a fresh developer org and the run tests to get the numbers.

**Comment by arangari** [comment]
Thanks... helpful. 
we can handle any extra as part of our release process

**Comment by afawcett** [comment]
Yes you should find it above 75%, we can re-open this issue if not. Thanks. 👍
