### ISSUE TITLE
Parent and Grand parent fields being queried for but not returned

### ISSUE THREAD

**Issue by liquidJbilling** [financialforcedev/fflib-apex-common#118]
Hi

I have the following parent->child relationships with some custom objects

1. Customer_Requirements__c is the parent of Request_Price_Quote__c
2. Request_Price_Quote__c is the parent of RPQ_Stage__c

I wanted to use the a RPQ Stage Selector to select the RPQ_Stage__c fields but also select the parent Request_Price_Quote__c and grandparent Customer_Requirements__c fields. 
The class compiles and runs but only the RPQ_Stage__c fields are selected/returned by the `Database.query(query)`. The Request_Price_Quote__r and Request_Price_Quote__r.Customer_Requirements_Document__r fields are not returned. 
In debug I can see the query string has all of the fields in it, again I've put in an example below.

```
        RPQ_Selector rpqSelector = new RPQ_Selector();
        CRDSelector crdSelector = new CRDSelector();

        String query = String.format(
                'select {0}, {1}, {2} ' +
                        'from {3} ' +
                        'where Id in :idSet ' +
                        'order by {4}',
                new List<String>{
                        getFieldListString(),
                        rpqSelector.getRelatedFieldListString('Request_Price_Quote__r'),
                        crdSelector.getRelatedFieldListString('Request_Price_Quote__r.Customer_Requirements_Document__r'),
                        getSObjectName(),
                        getOrderBy()
                });
        return (List<RPQ_Stage__c>) Database.query(query);
```

```
23:45:49.1 (86494456)|SOQL_EXECUTE_BEGIN|[48]|Aggregations:0|select Id,Name,Status__c,Stage_name__c,OwnerId,CreatedDate,Due_Date__c,Assigned_time__c,End_time__c,SLA_Flag__c,SLA_Status__c,Comment__c,CurrencyIsoCode, Request_Price_Quote__r.Id,Request_Price_Quote__r.Name,Request_Price_Quote__r.Due_Date__c,Request_Price_Quote__r.SLA_Flag__c,Request_Price_Quote__r.OwnerId,Request_Price_Quote__r.Customer_Requirements_Document__c,Request_Price_Quote__r.Current_stage__c,Request_Price_Quote__r.CurrencyIsoCode, Request_Price_Quote__r.Customer_Requirements_Document__r.Name,Request_Price_Quote__r.Customer_Requirements_Document__r.Id,Request_Price_Quote__r.Customer_Requirements_Document__r.OwnerId,Request_Price_Quote__r.Customer_Requirements_Document__r.Description__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Status__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Quotation_Type__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Net_Type__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Opportunity__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Opportunity_Name__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Opportunity_Number__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Contract_Length__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Contract_Term__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Off_Net_Parts__c,Request_Price_Quote__r.Customer_Requirements_Document__r.OPCO__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Days_to_price__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Request_Price_Quote__c,Request_Price_Quote__r.Customer_Requirements_Document__r.RPQ_Stage__c,Request_Price_Quote__r.Customer_Requirements_Document__r.CurrencyIsoCode from RPQ_Stage__c where Id in :idSet order by Name

```

**Comment by tfuda** [comment]
Sounds like a permission problem. Is your query being executed "with
sharing"? Are your selector classes configured to enforce CRUD and FLS?
Perhaps you don't have read access to the Request_Price_Quote__c and / or
Customer_Requirements_Document__c objects, or the particular records you
are trying to access are not shared with you. Can you run this query as a
user with "view all data" permission to see if that works?

On Thu, May 5, 2016 at 7:23 PM, liquidJbilling <notifications@github.com>
wrote:

> Hi
>
> I have the following parent->child relationships with some custom objects
>
>    1. Customer_Requirements__c is the parent of Request_Price_Quote__c
>    2. Request_Price_Quote__c is the parent of RPQ_Stage__c
>
> I wanted to use the a RPQ Stage Selector to select the RPQ_Stage__c fields
> but also select the parent Request_Price_Quote__c and grandparent
> Customer_Requirements__c fields.
> The class compiles and runs but only the RPQ_Stage__c fields are
> selected/returned by the Database.query(query). The
> Request_Price_Quote__r and
> Request_Price_Quote__r.Customer_Requirements_Document__r fields are not
> returned.
> In debug I can see the query string has all of the fields in it, again
> I've put in an example below.
>
>         RPQ_Selector rpqSelector = new RPQ_Selector();
>         CRDSelector crdSelector = new CRDSelector();
>
>         String query = String.format(
>                 'select {0}, {1}, {2} ' +
>                         'from {3} ' +
>                         'where Id in :idSet ' +
>                         'order by {4}',
>                 new List<String>{
>                         getFieldListString(),
>                         rpqSelector.getRelatedFieldListString('Request_Price_Quote__r'),
>                         crdSelector.getRelatedFieldListString('Request_Price_Quote__r.Customer_Requirements_Document__r'),
>                         getSObjectName(),
>                         getOrderBy()
>                 });
>         return (List<RPQ_Stage__c>) Database.query(query);
>
> 23:45:49.1 (86494456)|SOQL_EXECUTE_BEGIN|[48]|Aggregations:0|select Id,Name,Status__c,Stage_name__c,OwnerId,CreatedDate,Due_Date__c,Assigned_time__c,End_time__c,SLA_Flag__c,SLA_Status__c,Comment__c,CurrencyIsoCode, Request_Price_Quote__r.Id,Request_Price_Quote__r.Name,Request_Price_Quote__r.Due_Date__c,Request_Price_Quote__r.SLA_Flag__c,Request_Price_Quote__r.OwnerId,Request_Price_Quote__r.Customer_Requirements_Document__c,Request_Price_Quote__r.Current_stage__c,Request_Price_Quote__r.CurrencyIsoCode, Request_Price_Quote__r.Customer_Requirements_Document__r.Name,Request_Price_Quote__r.Customer_Requirements_Document__r.Id,Request_Price_Quote__r.Customer_Requirements_Document__r.OwnerId,Request_Price_Quote__r.Customer_Requirements_Document__r.Description__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Status__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Quotation_Type__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Net_Type__c,Request_Pr
>  ice_Quote__r.Customer_Requirements_Document__r.Opportunity__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Opportunity_Name__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Opportunity_Number__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Contract_Length__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Contract_Term__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Off_Net_Parts__c,Request_Price_Quote__r.Customer_Requirements_Document__r.OPCO__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Days_to_price__c,Request_Price_Quote__r.Customer_Requirements_Document__r.Request_Price_Quote__c,Request_Price_Quote__r.Customer_Requirements_Document__r.RPQ_Stage__c,Request_Price_Quote__r.Customer_Requirements_Document__r.CurrencyIsoCode from RPQ_Stage__c where Id in :idSet order by Name
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/financialforcedev/fflib-apex-common/issues/118>
>



-- 
Tom Fuda
Nine Summer
Email: tom@9summer.com
Phone: +1.203.361.9416
http://9summer.com : Accelerating innovative products to market.

**Comment by liquidJbilling** [comment]
@tfuda Thanks for your response, permissions weren't the issue but your answer helped me find the issue, which was in my code! The fields were being selected correctly, I was misled to thinking they were not because the System.debug() was not showing the relationship ('__r') fields. Thanks again.
