### ISSUE TITLE
Method does not exist or incorrect signature

### ISSUE THREAD

**Issue by tmichels** [financialforcedev/fflib-apex-common#121]
@afawcett Trying to create an account and a related contact as a unit of work. Here is a sample code:

fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
Account account = new Account();
account.Name = 'John Doe Household';
Account account = createAccount(register);
uow.registerNew(account);
Contact contact = new Contact();
contact.firstName = 'John';
contact.lastName = 'Doe';
contact.email = 'johndoe@mail.com';
uow.registerRelationship(contact, Contact.AccountId, account)

Error: Method does not exist or incorrect signature: [fflib_ISObjectUnitOfWork].registerRelationship(Contact, Id, Account)

Seems like Contact.AccountId is not seen as Schema.sObjectField but as Id.

**Comment by tfuda** [comment]
If you cast your result to an instance of fflib_SObjectSelector I believe this should work. The registerRelationship method is not defined for the fflib_ISObjectUnitIOfWork interface.

**Comment by tmichels** [comment]
@tfuda it is not the results that is failing is the parameter of Contact.AccountId that is not conforming to the method required inputs. Here is the registerRelationship method: https://github.com/financialforcedev/fflib-apex-common/blob/master/fflib/src/classes/fflib_ISObjectUnitOfWork.cls#L46

**Comment by tmichels** [comment]
@tfuda the parameter is throwing an error as it is expecting an Schema.sObjectField relatedToField. 

Here is the registerRelationship method: https://github.com/financialforcedev/fflib-apex-common/blob/master/fflib/src/classes/fflib_ISObjectUnitOfWork.cls#L46

**Comment by frup42** [comment]
Apex case insensitivity rears its ugly head again. Contact.AccountId is usually an SObjectField. But here, the Contact SObjectType is shadowed by the contact variable...
``Contact contact = new Contact();``

Change the variable name and it should be all good in the hood. Closing this, but obviously reopen if it doesn't fix things

**Comment by tmichels** [comment]
@frup42 that worked 👍

**Comment by Sahityatarumani** [comment]
@dfruddffdc you saved me from going insane (facepalm).

**Comment by wimvelzeboer** [comment]
Alternatively you could add Schema:
> uow.registerRelationship(contact, **Schema.**Contact.AccountId, account)

**Comment by Sahityatarumani** [comment]
@wimvelzeboer Thanks! that does make sense.
