### ISSUE TITLE
You have uncommitted work pending

### ISSUE THREAD

**Issue by tmichels** [financialforcedev/fflib-apex-common#125]
I am creating a new Account and if the account creation fails the exception is posted to an external service using the callout feature. Here is the snippet:

```
try{
    fflib_ISObjectUnitOfWork uow = BrightPlan_Rest_App.UnitOfWork.newInstance();
      Account bpAccount = createAccount(userInfo);
      uow.registerNew(bpAccount);
      uow.commitWork();
catch(Exception ex){
     LoggingService.logException(ex);
}
```

LoggingService calls out to external service. I see the follow error message:

> "message": "System.CalloutException: You have uncommitted work pending. Please commit or rollback before calling out"

When I look at the code it seems like the commitWork handles rollback:
```
catch (Exception e){
			// Rollback
			Database.rollback(sp);
			// Throw exception on to caller
			throw e;
}
```

Any suggestions?

**Comment by tfuda** [comment]
This is a platform thing, not an fflib issue. You can't call out to a web service after you've executed a DML operation. Nor can you call out to a web service if you've created a Savepoint. This is a limitation of the Salesforce platform (by design). Try annotating your LoggingService.logException method with the @future(callout=true) annotation. I think it should work then.

**Comment by tmichels** [comment]
@tfuda thanks for clarifying. I will make the change thanks.

**Comment by tfuda** [comment]
One thing that might cause you problems is that your logException method takes an instance of Exception as its argument. I think future methods only accept primitive types or collections of primitives as arguments (like String, Integer, Decimal, etc). You may not be able to pass an Exception into your future method. You might need to pass the Exception message and stack trace as String parameters.

**Comment by afawcett** [comment]
Thanks @tfuda for responding to this! Go community! 👍
