### ISSUE TITLE
Set ordering for Subselect

### ISSUE THREAD

**Issue by dlisovsky** [financialforcedev/fflib-apex-common#140]
Hi Team,

Default ordering for Subselect is 'Name ASC NULLS FIRST'.

It would be great to have a method to clear ordering OR add an index parameter to the addOrdering method.

Please see the code:

`fflib_QueryFactory donationRecQueryFactory = newQueryFactory()
    .setCondition('Status__c = :openStatus');

fflib_QueryFactory opportunityQueryFactory = new OpportunitySelector()  
    .addQueryFactorySubselect(donationRecQueryFactory)
    .addOrdering(
        Opportunity.CreatedDate,
        fflib_QueryFactory.SortOrder.DESCENDING,
        true
    )
    .setLimit(1);`

Generates: 

`SELECT ...,  (SELECT ... FROM Opportunities__r ORDER BY Name ASC NULLS FIRST , CreatedDate DESC NULLS LAST LIMIT 1) FROM Recurring_Donation__c ...`

BUT

I want to order subselect by CreatedDate.

Please have a look at the suggestions:

`.addQueryFactorySubselect(donationRecQueryFactory)
        .clearOrdering()
    .addOrdering(
        Opportunity.CreatedDate,
        fflib_QueryFactory.SortOrder.DESCENDING,
        true
    )
    .setLimit(1);`
`

OR

`.addQueryFactorySubselect(donationRecQueryFactory)
    .addOrdering(
                0, /* First ORDERING */
        Opportunity.CreatedDate,
        fflib_QueryFactory.SortOrder.DESCENDING,
        true
    )
    .setLimit(1);`
`

Thanks,
Dmitry Lisovsky

**Comment by afawcett** [comment]
@dlisovsky this sounds like a good idea, any reason why we should not keep this open and mark it as an enhancement? Happy to do so. Just wondering why you closed it?

**Comment by ironal** [comment]
Hi, this actually would be very useful. Has it been implemented? Thank you.
