### ISSUE TITLE
fflib_SObjectMocks.SObjectUnitOfWork: Class must implement the public interface method

### ISSUE THREAD

**Issue by putskiz** [financialforcedev/fflib-apex-common#146]
Trying to deply Apex Common right after having deployed ApexMocks and got this error :

Failures:
classes/fflib_SObjectMocks.cls(45,23):f: void registerDirty(SObject, Schema.SObjectField, SObject) from fflib_ISObjectUnitOfWork
classes/fflib_ApplicationTest.cls(84,41):Dependent class is invalid and needs recompilation:
fflib_SObjectMocks: line 45, column 23: fflib_SObjectMocks.SObjectUnitOfWork: Class must implement the public interface method: void registerDirty(SObject, Schema.SObjectField, SObject) from fflib_ISObjectUnitOfWork

**Comment by isalew** [comment]
Was just about to report the same thing. I receive the same error when attempting to deploy. It appears to be an issue related to [the following commit](https://github.com/financialforcedev/fflib-apex-common/commit/4c385385ac94487c566ed06573ddd0f096316f4b#diff-0b5f8b51366ab628ee361342fb2bee67).

**Comment by isalew** [comment]
@putskiz, for a quick workaround, you can download [the following version of the repository](https://github.com/financialforcedev/fflib-apex-common/tree/0a9d4e83a4b35c940ec02450d32b8969a0dbe53a), from before the offending commit, and deploy using the force.com migration tool. Just deployed successfully for me.

**Comment by afawcett** [comment]
Working on this fix, will also get Travis setup on this repo! ;-)

**Comment by afawcett** [comment]
This has been fixed.
