### ISSUE TITLE
Offset in Queryfactory [question/improvement]

### ISSUE THREAD

**Issue by ApraChris** [financialforcedev/fflib-apex-common#159]
Hi,

first of let me say a huge thanks for this amazing library! It really makes Apex software development a lot easier.
A question about the query factory though: Is there a reason there's a private propery "offset" (Integer) but no getter/setter and it's not included when the query is built?
I cannot seem to find any comment marking it as "currently not supported" or something.
I ended up just adding it to the class and it seems to work fine - is there a scenario I'm missing?

Regards
Chris

**Comment by afawcett** [comment]
Thanks @ApraChris, looks like @JonnyPower sorted you out! Thanks both! 👍
