### ISSUE TITLE
Granular Disable of Trigger CRUD Security 

### ISSUE THREAD

**Issue by daveerickson** [financialforcedev/fflib-apex-common#165]
I'm happy there is a way to disable this per domain class, but am hoping there is a way to only allow this on some methods.

Use Case:
We are a financial institution and use Asset to describe our investments purchased by our customers. We use the Parent Asset lookup to tie the monthly interest payments to the Asset record describing the investment. We have code that can create out the future interest records for the life of the investment based upon term length, payment frequency, etc, and also update these child interest records if a value changes.

For compliance reasons our operations team can read, create, and edit Asset records, but cannot delete them. This throws an error with the after delete CRUD check in the SObjectDomain class. The easy work around has been to call Configure.disableTriggerCRUDSecurity() is the constructor as has been pointed out. I've even gone to the lengths to test that an operations user cannot do any sort of API delete with this setting, as expected. So, I'm comfortable using this as a solve in production, but I'd really like a way to granularly allow an exception to the CRUD enforcement.

I'm hoping such a solve already exists and I'm just unable to find documentation or examples. Otherwise I'd be interested in a discussion on how this could possibly be implemented. Much appreciated!

**Comment by afawcett** [comment]
Thanks @daveerickson, no your not missing anything. I think its best to create your own base class, which disables the standard functionality and overrides the virtual handleXXX methods (call super to retrain the base class behaviour) then add some booleans in your own base class constructor to add a more granular way. Or if this is a one off, just override these in your Assets class and explicit checks where needed. Hope this helps! 👍
