### ISSUE TITLE
Deployment Problem might related to #166

### ISSUE THREAD

**Issue by nutchanon-pho** [financialforcedev/fflib-apex-common#167]
This is what I got when I am trying to deploy fflib-apex-common after the apex-mock. It might have something to do with #166 .

Deployment Started
Status: Queued 
Status: InProgress 
Status: Completed 
Deployment Complete
Failures:
classes/fflib_SObjectMocks.cls(45,23):Class fflib_SObjectMocks.SObjectUnitOfWork must implement the method: void fflib_ISObjectUnitOfWork.registerRelationship(Messaging.SingleEmailMessage, SObject)
classes/fflib_ApplicationTest.cls(45,23):Dependent class is invalid and needs recompilation:
 Class fflib_SObjectMocks : Class fflib_SObjectMocks.SObjectUnitOfWork must implement the method: void fflib_ISObjectUnitOfWork.registerRelationship(Messaging.SingleEmailMessage, SObject)
fflib/src
fflib/src/package.xml
fflib/src/classes

**Comment by nutchanon-pho** [comment]
I have tried deploying commit no. 736657638f9719c8ae4ed3ef68166d9b361d8213
and it worked. So, the new pull request is the problem.

**Comment by martykopka** [comment]
Im getting the same problem when trying to do the trailhead and deploy

**Comment by martykopka** [comment]
Its okay i worked it out. IN the deploy tool on heroku just need to use: 736657638f9719c8ae4ed3ef68166d9b361d8213 
as the commit value to deploy.  That worked for me and was now able to deploy.

**Comment by nutchanon-pho** [comment]
The merge request fixed the problem. This issue can be closed.

**Comment by afawcett** [comment]
@martykopka thats cool, didn't now the tool supported that! 👍
