### ISSUE TITLE
Tests fail because of Person Accounts

### ISSUE THREAD

**Issue by ejwill** [financialforcedev/fflib-apex-common#170]
I have Person Accounts enabled in my org which causes Account insert errors for fflib_MatcherDefinitionsTest, fflib_QueryFactorTest, fflib_SObjectSelectorTest.  The issues are as follow
 
-  the tests are trying to insert Accounts but when Person Accounts are enabled you have to include what type of record you are inserting
- QueryFactory test where Accounts, Contacts, and Tasks are being created to test child queries.  The issue is with creating a contact for the account that was just created but contacts are automatically created for Person Accounts.

I will work on a fix over the next few days to dynamically change the test methods that fail because of Personal Accounts and submit a PR

**Comment by ImJohnMDaniel** [comment]
@ejwill, what type of errors are you getting?  I have Person Accounts as well and have never had any issues.

**Comment by ejwill** [comment]
@ImJohnMDaniel this is an example from fflib_MatcherDefinitions

Errors:
System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, record type missing for: Customer: []
Stack Trace: Class.fflib_MatcherDefinitionsTest: line 52, column 1

Here is an example from fflib_QueryFactor
Error: System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, record type missing for: Customer: []
Stack Trace: Class.fflib_QueryFactoryTest.addChildQueriesWithChildRelationshipNoAccessibleCheck_fail: line 378, column 1

**Comment by ImJohnMDaniel** [comment]
@ejwill -- Does the user that is executing the unit test have a default record type set for when it creates a new Account/Person Account record?

**Comment by ejwill** [comment]
@ImJohnMDaniel I don't believe so

**Comment by ImJohnMDaniel** [comment]
@ejwill -- This is probably the issue.  Try changing the user that is running the tests so that they have a default record type to use when creating PersonAccount records.

**Comment by ejwill** [comment]
@ImJohnMDaniel I checked I do have a default setup to Person Account and I turned off the trigger that another team has created on the Account object but I still get the error.  I think it makes sense to change the tests to specify a record type if Person Accounts are enabled in an org just in case someone does not have a default set.

**Comment by ImJohnMDaniel** [comment]
@ejwill  I would agree if everyone is having the same issue you describe but this is the first that I have seen of this from anyone.  As I mentioned, I have been running this project's unit tests in a Person Accounts enabled org for over 9 months now.

I had a similar issue with a user just this past weekend.  The exception message was the same as what you show here; record type missing during an Account create event.  Going to the user's profile and setting the "record type setting" for the Account object to at least one Account record type available solved the issue.  That is why I was suggesting to check that there is a default record type.

Also, not every org has record types on the Account; much less have Person Accounts activated.  Adjusting the unit tests to specify a default record type would not make sense.

Any suggestions @afawcett, @dfruddffdc, @capeterson ??

**Comment by ejwill** [comment]
@ImJohnMDaniel I'll do some more research into my org; there is another team working in the same org that may have done something that I don't know about.  

My idea of changing the tests would be to put a check see if Person Accounts are created or not.  Then have if/else in the creation of data for the tests that fail

**Comment by ImJohnMDaniel** [comment]
@ejwill -- does the executing test user have a "Business Account Default Record Type" set as well as a "Person Account Default Record Type"??

**Comment by ejwill** [comment]
@ImJohnMDaniel no only Person Account has a default for record type

**Comment by ImJohnMDaniel** [comment]
@ejwill - That is the issue.  I was able to recreate the issue over here as well.  Give the execution user the default "Business Account" for the "Business Account Default Record Type" value.  That should fix the tests.

**Comment by ImJohnMDaniel** [comment]
Awesome.  Glad to hear it.

**Comment by mk4ugithub** [comment]
The solution posted here (adjust the record type for the execution user) helped me after 2 years. Thank you!

**Comment by nvuillam** [comment]
Updating profile **System Administrator** to define `Person Account` as a default record type (instead of `master` value) did the job for me :)
