### ISSUE TITLE
Intentions about SalesforceDX support/configuration?

### ISSUE THREAD

**Issue by ImJohnMDaniel** [financialforcedev/fflib-apex-common#174]
Questions for @afawcett, @dfruddffdc, and @phardakerffdc:
- Now that SalesforceDX is GA, what is the intention on supporting or reconfiguring the project to a SalesforceDX approach?
- Would that fork include the code from the [ApexMocks](https://github.com/financialforcedev/fflib-apex-mocks) project?
- Will the code base move to a packaged model when 2nd Generation Packaging goes GA so that we could include in our code base simply as a package installation?

I can certainly change my fork to support SalesforceDX but I would rather avoid doing that if you are going to convert to SalesforceDX approach or spin off a SalesforceDX branch.

Any input on your thoughts and plans for this codebase would be appreciated. 

Cheers!

**Comment by daveespo** [comment]
I'm a fan of a SalesforceDX branch, but I think that it's going to be a long time before we can turn our back on the MDAPI project structure. First-generation packaging is going to be around a while and any of us with existing packages that want to migrate to second-generation will have to wait until at least Summer '18, probably longer, before those projects can be converted.

**Comment by ImJohnMDaniel** [comment]
@daveespo, that makes sense.
