### ISSUE TITLE
Does not have a no-arg constructor

### ISSUE THREAD

**Issue by Xtremefaith** [financialforcedev/fflib-apex-common#178]
I don't understand why I have this issue. In my service implementation class I have the following method:

    public List<Account> getAccounts(Set<Id> ids){
        fflib_ISObjectDomain accounts = 
            Accounts.newInstance(
                AccountsSelector.newInstance().selectById( ids ));
        return accounts.getRecords();
    }

My unit test fails with the following error:

`System.TypeException: Accounts does not have a no-arg constructor`

My **Accounts.cls** looks like this:

	public with sharing class Accounts extends fflib_SObjectDomain
		implements IAccounts {

		public static IAccounts newInstance(List<Account> sObjectList) {
			return (IAccounts) Application.Domain.newInstance(sObjectList);
		}
		
		public Accounts(List<Account> sObjectList) {
			super(sObjectList, Account.SObjectType);
		}
		
	}

Judging from from the sample code I've seen I don't see what I'm doing wrong. It seems I just need to add a 0-argment constructor but I don't understand why and I don't see any sample of that. Any advice on this would be awesome! Thanks

In addition, my trouble shooting has taken me to the `fflib_Application.cls` to the following lines

    Type domainConstructorClass = m_sObjectByDomainConstructorType.get(domainSObjectType);
    (fflib_SObjectDomain.IConstructable) domainConstructorClass.newInstance();

From there I debugged the following:

    System.debug('domainSObjectType: '+domainSObjectType);

And as I would expect it came back with `Account`

One comment I'm wondering if it has any value to the conversation is posted [here](https://salesforce.stackexchange.com/questions/51707/how-to-create-object-by-its-name#comment68096_51708)

**Comment by ImJohnMDaniel** [comment]
Hey @Xtremefaith, is your unit test failing during a DML op on the Account records?

Is the domain object code that you listed above all there is for the Accounts class or is it just a snippet?  The reason that I ask is that I would normally expect to see the following `Constructor` inner class as part of a `fflib_SObjectDomain` class.

```
    public class Constructor implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new Accounts(sObjectList);
        }
    }
```

**Comment by Xtremefaith** [comment]
Hey @ImJohnMDaniel thanks for the response. So my `Accounts.cls` is based on the sample [here](https://github.com/financialforcedev/fflib-apex-common-samplecode/blob/master/fflib-sample-code/src/classes/Accounts.cls). This is my test class that is failing:

	@IsTest
	public with sharing class AccountsServiceTest {
		
		@IsTest
		private static void AccountsService_getAccounts() {
			//! Given
			/* Create mocks */
			fflib_ApexMocks mocks = new fflib_ApexMocks();
			IAccounts mockDomain = (IAccounts)mocks.mock(Accounts.class);
			IAccountsSelector mockSelector = (IAccountsSelector)mocks.mock(AccountsSelector.class);

			/* Configure the application to use mocks */
			Application.Domain.setMock(mockDomain);
			Application.Selector.setMock(mockSelector);

			/* Generate a generic account id */
			Id aid = fflib_IDGenerator.generate(Account.SObjectType);
			
			mocks.startStubbing();
			List<Account> accountsList = new List<Account> {
				new Account(
					Id = aid,
					Name = 'Test Account'
				) 
			};
			mocks.when(mockDomain.sObjectType()).thenReturn(Account.SObjectType);
			mocks.when(mockSelector.selectById(aid)).thenReturn(accountsList);
			mocks.stopStubbing();
			
			//! When
			AccountsASP.getAccount(aid);   
                        // I refer to the ___Service.cls as my ____ASP (Application Service Provider) and the 
                        // ______Impl.cls as my _____Service.cls (just for clarification here).

			//! Then
			/* Verify services were called */
			( (IAccountsSelector) mocks.verify(mockSelector, 1) ).selectById( aid );

		}

	}


I see that construct in the `fflib_SObjectDomain`, therefore I thought that was accounted for when extended that class. Also again, I don't see any examples that show that.

**Comment by Xtremefaith** [comment]
I found an example of what you were referring to in the `Opportunities.cls` from the sample repo so perhaps the `Accounts.cls` I was using was just outdated. So I went ahead and added it and the issue seemed to be resolved but now I'm back to another error, apparently the mock still isn't being called :(

`fflib_ApexMocks.ApexMocksException: Expected : 1, Actual: 0 -- Wanted but not invoked: AccountsSelector__sfdc_ApexStub.selectById(Id)`

Since I have everything posted here already, any idea as to why this is?

**Comment by dfruddffdc** [comment]
Here's the problem: [fflib_Application - line 232](https://github.com/financialforcedev/fflib-apex-common/blob/master/fflib/src/classes/fflib_Application.cls#L232).

The Domain and Selector factories key the real and mock implementors using their SObjectType. So make sure you stub the `fflib_ISObjectSelector.sObjectType()` and `fflib_ISObjectDomain.sObjectType()` methods before registering the mocks.

```java
// Add this:
mocks.startStubbing();
mocks.when(mockDomain.sObjectType()).thenReturn(Account.SObjectType);
mocks.when(mockSelector.sObjectType()).thenReturn(Account.SObjectType);
mocks.stopStubbing();

/* Configure the application to use mocks */
Application.Domain.setMock(mockDomain);
Application.Selector.setMock(mockSelector);
```

I generally set up all the mock expectations before registering them in the application factories, which avoids this issue but also feels a bit cleaner to me.

Thanks and good luck!
