### ISSUE TITLE
DML Used on Empty List

### ISSUE THREAD

**Issue by tmowbrey** [financialforcedev/fflib-apex-common#205]
https://github.com/financialforcedev/fflib-apex-common/blob/43d2bc897db89367384e70d8cda8439ec4ef66bc/fflib/src/classes/fflib_SObjectUnitOfWork.cls#L90-L98

I'm curious to understand if we should check for null or empty list before completing the dml operation given that is is possible to call uow.CommitWork() and have empty lists. If that happens, the library utilizes extra limits for dml when not needed.

**Comment by rsoesemann** [comment]
No limits are used on empty lists. See https://salesforce.stackexchange.com/questions/19399/any-reason-to-skip-dml-on-empty-lists
