### ISSUE TITLE
"QueryException: duplicate field" as Selectors ignore prefix on same-name fields

### ISSUE THREAD

**Issue by rsoesemann** [financialforcedev/fflib-apex-common#218]
_Note: This is really hard to reproduce therefore I only report it and not provide a fix PR for this._

I have a `CustomObject__c` in an managed package with Namespace `NS`. In the package this object hat a field `NS__MyField__c`. The customer added `MyField__c` in his org where the package is installed.

We have a CustomObjectsSelector where we recently had to switch from listing needed fields to insert ALL fields (SELECT*):

```java
public class CustomObjectsSelector extends fflib_SObjectSelector {

	public List<SObjectField> getSObjectFieldList() {
		return type.getDescribe().fields.getMap().values();
	}

	public List<CustomObject__c> byIdWithParent(Set<Id> ids) {
		fflib_QueryFactory qf = newQueryFactory();
		new ParentsSelector().configureQueryFactoryFields(qf, 'lkp_Parent__c');
		return (List<CustomObject__c>) Database.query(qf.setCondition('Id IN :ids').toSOQL());
	}
}
```

The strange symptom is as the byIdWithParent() method fails in the customer org with

> System.QueryException: duplicate field selected: NS__MyField__c

I tracked this down to https://github.com/financialforcedev/fflib-apex-common/blob/master/fflib/src/classes/fflib_QueryFactory.cls#L127 where the SObjectField is converted to a string using` field.getDescribe().getName()`. 

Looks like this behaves like `field.getDescribe().getLocalName()` now? #Confused

**Comment by daveespo** [comment]
This is not a fflib QueryFactory or SObjectSelector problem. From managed package Apex code, you can't distinguish between unmanaged fields with the same name as your managed fields in a SOQL SELECT clause. It's just one of those limitations that's always existed.

We usually hit it when we support Field Sets in some piece of application code and the customer adds one of their unmanaged fields to the Field Set that matches the name of one of our managed fields .. but your repro case of "SELECT *" would have the same problem.

**Comment by rsoesemann** [comment]
I just can't believe that. But I fully believe you. Is there anything you can point me to where this is documented. Or how can I easily reproduce this? In my packaging org I can't. It only happens in installed customer orgs.

And do you have a means to prevent this?

**Comment by daveespo** [comment]
When we first hit this, the only thing we could find was this Stackexchange posting (read the comment thread in the first Answer)

https://salesforce.stackexchange.com/questions/13353/dynamic-soql-queries-and-managed-namespaces

There's a vague Knowledge article about it:

https://help.salesforce.com/articleView?id=000181257&language=en_US&type=1

You can't test or reproduce it in your scratch org, packager org, or DE org. It can only be reproduced in a subscriber org.

As for prevention -- nope -- we just have a troubleshooting step when a customer cause the application to break down by doing this and we tell them to rename the field :-/

**Comment by rsoesemann** [comment]
Thanks for your great help. I probably would have never found out this by myself.

**Comment by ImJohnMDaniel** [comment]
I know that @capeterson is very aware of this issue as well.  I have seen it myself.

Hey Chris -- anything on the Apex roadmap that might help with this issue?
