### ISSUE TITLE
Order of DML Operation

### ISSUE THREAD

**Issue by tmowbrey** [financialforcedev/fflib-apex-common#51]
Currently there is no way (that I can tell) for someone to control the order of the DML operations in fflib_SObjectUnitOfWork. I've found myself in a situation in which I would like to complete all my updates first and then complete the inserts and/or deletes. Any thoughts on resolving this? Should it be resolved?

**Comment by afawcett** [comment]
Hmmmm interesting question, can you give some more background as to your use case?

**Comment by afawcett** [comment]
I'd like to see some use cases for this proposal if you have some?

**Comment by tmowbrey** [comment]
I'd like to close this out, i've managed to solve my use cases using the current functionality.
