### ISSUE TITLE
Test Class for fflib_Application

### ISSUE THREAD

**Issue by tmowbrey** [financialforcedev/fflib-apex-common#55]
Does anyone have a test class for fflib_Application?

**Comment by afawcett** [comment]
Apologies, looks like i forgot to add this, there is indeed a test class for this. I've marked this issue as a bug and will get one added.

**Comment by tmowbrey** [comment]
Thanks Andrew!

**Comment by tmowbrey** [comment]
Bump. Just wanted to see if this test class was still going to be added. Thanks!

**Comment by afawcett** [comment]
Done, 100% class coverage! :+1:
