### ISSUE TITLE
InvalidFIeldException UserRecordAccess on a Custom Object

### ISSUE THREAD

**Issue by maximorojr** [financialforcedev/fflib-apex-common#64]
I need to select a custom object with UserRecordAccess as a foreign key, but I can't get it from Salesforce SObjectDescribe and SObjectFIeldDescribe, I don't know why... if I can write a select into [] and get that relationship data, why can't I get it from describe? Whatever... I want to use the QueryFactory but I'm getting the InvalidFieldException caused by the problem that I told above through the method fflib_QueryFactory.getFieldToken(String fieldName). I don't want to write  a "hard-coded select" that is the only solution that I found until now. Can someone help me?

**Comment by ImJohnMDaniel** [comment]
@maximorojr Can you post an example of what you have attempted thus far?

**Comment by capeterson** [comment]
I believe you just need to increase the platform API that `fflib_QueryFactory` and `fflib_SObjectDescribe` are running against. That field is new(ish) and I don't think exists until > APIv30.0. Give that a try?

**Comment by maximorojr** [comment]
@ImJohnMDaniel 
Here is an example, try to create a method to the SELECT below on an AccountsSelector using the fflib_QueryFactory.

```
SELECT Id, Name, UserRecordAccess.HasReadAccess, UserRecordAccess.HasTransferAccess, UserRecordAccess.MaxAccessLevel
FROM Account
```

Should be something like this:

```
public List<Account> selectByIdWithUserRecordAcess(Set<Id> idSet)
fflib_QueryFactory accountsQueryFactory = newQueryFactory();
UserRecordAccessesSelector userRecordAccessesSelector = (UserRecordAccessesSelector) UserRecordAccessesSelector.newInstance();
userRecordAccessesSelector.configureQueryFactoryFields(accountsQueryFactory,'UserRecordAccess');
registrationNumbersQueryFactory.setCondition('Id IN :idSet');
return (List<Account>)Database.query(accountsQueryFactory.toSOQL());
}
```

@capeterson I tried to update the API Version to the latest, but it still not working. I believe it's Salesforce bug... because when I try to get the describe through executing an anonymous apex code, it doesn't work too. 
I've opened a discussion in Developer Forum.<a href="https://developer.salesforce.com/forums/#!/feedtype=SINGLE_QUESTION_DETAIL&dc=Developer_Forums&criteria=ALLQUESTIONS&id=906F0000000BQC7IAO"> Link to the discussion</a>

**Comment by maximorojr** [comment]
I've created an <a href="https://success.salesforce.com/ideaView?id=08730000000sXtqAAE">Idea</a> to implement that. Please up vote my idea. :+1:

**Comment by afawcett** [comment]
Upvoted! :+1:

**Comment by afawcett** [comment]
@maximorojr i think with identifying a platform need and raising the idea, we are done here? Let me know if you think otherwise and we can re-open. Thanks again! 👍

**Comment by maximorojr** [comment]
We are done here! Thanks!
