### ISSUE TITLE
QueryFactory - selectAllFields

### ISSUE THREAD

**Issue by tmowbrey** [financialforcedev/fflib-apex-common#75]
Hi Everyone,

What are your thoughts for adding a new method called selectAllFields that does a describe and pulls all fields for the given SObjectType passed in?

@capeterson @afawcett 

Tyler

**Comment by tfuda** [comment]
I actually tried something similar to this with one of my SObjectSelector classes, and I ran into problems. There are a couple of fields (I'll have to dig them up) that appear in the describe result, but if you embed them in a SOQL query you'll get an unknown field error if the calling class isn't at the proper API version number. Basically they are newer standard fields added to SObject in API version 31.0 or something, and some of my Apex classes were still on older API versions. I'm not saying it's not a good idea, but I did run into some issues with it. I'll see if I can dig up the specifics.

**Comment by capeterson** [comment]
I'm on the fence about it. On one hand there are occasionally legitimate uses, but on the other it helps re-enforce really bad practices, and on large objects will end up throwing query too complex errors (yes, that [really happens](https://github.com/capeterson/Grey-Tab/issues/23)) once you get too many fields.

I'm increasingly considering a new subclass of query factory that adds functionality useful in debugging. The sorting of fields when generating SOQL has proved to be rather expensive, and really only useful in test contexts, which would be the same type of scenarios I could see `selectAllFields` being useful in. Calling it something like `fflib_DebugQueryFactory` would make it sound sufficiently scary to ward off overuse in production code (I hope), and as long as it was a subclass it would be amenable to some basic dependency injection as needed.

**Comment by Autobat** [comment]
How about a simple interface to allow query by field set?  This would allow it to be both configurable and also scale to the largest orgs.

**Comment by tmowbrey** [comment]
Query by fieldset is already included and seems like continuing with that seems
the best course of action.

Please Excuse Typos - Sent via Mobile Device On Mon, Aug 03, 2015 at 8:48 PM, Autobat < notifications@github.com [notifications@github.com] > wrote:
How about a simple interface to allow query by field set? This would allow it to
be both configurable and also scale to the largest orgs.

—
Reply to this email directly or view it on GitHub
[https://github.com/financialforcedev/fflib-apex-common/issues/75#issuecomment-127470089] .[https://github.com/notifications/beacon/AC5CYobJpo3HOLCskkgJ-bS5KWqebeB-ks5okC2EgaJpZM4FkttL.gif]

**Comment by capeterson** [comment]
@Autobat: as @tmowbrey mentioned, field set support is in since the initial release. See https://github.com/financialforcedev/fflib-apex-common/blob/master/fflib/src/classes/fflib_QueryFactory.cls#L261-L278

Fun fflib trivia: that's actually the entire reason this class started; for merging multiple field sets into a single query.

**Comment by Autobat** [comment]
Ah fantastic.  I'm still learning all the features of this library as you can easily tell :)

**Comment by cdcarter** [comment]
In a similar vein, I just added 

	public fflib_QueryFactory selectCreatableFields() {
		List<Schema.SObjectField> allFields = fflib_SObjectDescribe.getDescribe(this.table).getFieldsMap().values();
		for(Schema.SObjectField field : allFields) {
			Schema.DescribeFieldResult fd = field.getDescribe();
			if(fd.isCreateable()) {
				this.fields.add(new QueryField(field));
			}
		}
		return this;
	}

to QueryFactory. It selects all createable fields, which is vaguely useful for cloning operations. It's nice to allow admins to create new fields and not have to add them to a fieldset just to make sure their cloning works.

**Comment by capeterson** [comment]
@cdcarter how do you feel about substantially all of queryfactory being virtual? This would let you make subclasses with extra behavior that we might be a bit wary of incorporating into the mainline of the repo, but without the hassle of manually merging going forwards.

Also, I believe we're slowly headed in a direction that might let us do this a bit more genericly, hope to have news on that soonish. Sorry to be so vague about it but still need to finalize some plans before I can share them.

**Comment by cdcarter** [comment]
@capeterson -- on one hand, more classes is more mental overhead, but if you aren't interested in mainlining this, it's a better solution than manual patches, you're right!

**Comment by afawcett** [comment]
Yeah i had a chat with another contributor about making more of this library virtual and on balance decided to remain use case driven and avoid the potential future downsides from a testing and sustainability perspective. My vote is to make things virtual where we can look back and say its for this use case or to allow this plugin etc. So grow it based on use case driven motivations.

**Comment by afawcett** [comment]
How about a fflib_QueryFactoryUtils (i know i know bad name, but this is a library and not business logic really). We can host some of these type of methods on that, fflib_QueryFactoryUtils.selectCreatableFields(qf); and add some comments and docs to the class about how each needs to be used with care regarding best practices etc. I hear what Chris is saying, and i think this library has to help encourage best practices, so its a fine line, between being a useful library and managing this desire.

**Comment by ejwill** [comment]
I know its 2 years later but was anything done with this?  I am working on a cloning operation what was mentioned earlier as a possible use case where returning all fields in a selector would be very useful.

**Comment by afawcett** [comment]
@ejwill sorry nothing as far as i am aware and my feelings are still the same. Happy to accept a PR for a fflib_QueryFactoryUtils class per my suggestions above. I'll close this out for now, but for sure this does not mean we cannot move on something like a util class per my suggestions here. 👍

**Comment by afawcett** [comment]
@ejwill thanks for the update! 👍

**Comment by cropredyHelix** [comment]
> In a similar vein, I just added
> 
> ```
> public fflib_QueryFactory selectCreatableFields() {
>     List<Schema.SObjectField> allFields = fflib_SObjectDescribe.getDescribe(this.table).getFieldsMap().values();
>     for(Schema.SObjectField field : allFields) {
>         Schema.DescribeFieldResult fd = field.getDescribe();
>         if(fd.isCreateable()) {
>             this.fields.add(new QueryField(field));
>         }
>     }
>     return this;
> }
> ```
> 
> to QueryFactory for a client of mine. It selects all createable fields, which is vaguely useful for cloning operations. It's nice to allow admins to create new fields and not have to add them to a fieldset just to make sure their cloning works.

FYI - this no longer works if running an older version of fflib_QueryFactory as inner class QueryField was removed for performance improvements
