### ISSUE TITLE
Inconsistent performance when constructing QueryFactory

### ISSUE THREAD

**Issue by daveespo** [financialforcedev/fflib-apex-common#79]
We have an ongoing Case with Tier 3 (I'll spare the rant) regarding a performance problem that we're seeing when constructing a new fflib_QueryFactory

Here's a sample Selector:

````java
public with sharing class TicketOrdersSelector extends fflib_SObjectSelector {
  public TicketOrdersSelector() {
    super();
  }
  
  public TicketOrdersSelector(Boolean includeFieldSetFields) {
    super(includeFieldSetFields);
  }
  
  List<Schema.SObjectField> getSObjectFieldList() {
    return new List<Schema.SObjectField> {
      TicketOrder__c.Account__c,
      TicketOrder__c.AmountDue__c,
/* <snip ... about 60 additional fields/> */
      TicketOrder__c.UserAgent__c
    };
  }
  
  Schema.SObjectType getSObjectType() {
    return TicketOrder__c.SObjectType;
  }
  
  public List<TicketOrder__c> selectById(Set<Id> idSet) {
    return (List<TicketOrder__c>) selectSObjectsById(idSet);
  }
}
````

We're seeing that calling newQueryFactory() on an instance of TicketOrdersSelector is taking 200-300ms.

We boiled down the problem to the use of a Set to back the list of QueryFields in QueryFactory. QueryField implements hashCode() and equals() but upon instrumenting those two methods, we found that hashCode() wasn't always called but equals() was -- up to N times -- basically behaving more like a List than a Set from a performance perspective. Concretely, this meant that equals() was being called (N^2)/2 times -- a real drag if you have 50+ fields in your Selector

Further debugging showed that the behavior was affected by the logging level. Setting Apex Code to FINEST would result in the N^2 behavior while setting it to DEBUG wouldn't. But this wasn't how we had our DEs configured -- they usually had DEBUG set as the default level. 

Further investigation lead to the log override we were setting on fflib_QueryFactory to set all log levels to NONE (so that we didn't pollute all of our logs with METHOD_ENTRY/METHOD_EXIT). It seems like setting the overrides for the class caused it to revert back to the N^2 behavior. Without the log override, it was performant (though noisy).

The words from Tier 3 thus far are:

> This is Working as Designed (WAD). The difference comes from underlying Map representations. We have two representations for Map.
>
>One keeps the objects in a Map in the interpreter (apex) native representation. And in this case, if the put() method (or add() ) is called to it, uniqueness of keys are determined by using both of hashCode() and equals(). (A value returned by the hashCode() method is used to determine a bucket, and the equals() method is used to identify objects in the same bucket.) 
>
>Once a Map is marshaled, the other representation is used.In this representation, in the put() method call, we traverse all objects in a Map and linearly check uniqueness of keys using the equals() method if a user defined key is used.That's why you don't see the hashCode() method being called but see the equals() method calls in our testcase. (The Map/set object is marshaled when trying to generate a debug message for local variable assignments.) 
>
>However, the latter representation does not violate the Map contract. Any method call defined in the Map class works as per doc.

This obviously disregards the fact that we're not generating debug messages for QueryFactory -- we've explicitly disabled it. Yet it still behaves as though it's set to FINEST even when the entry point log level is DEBUG.

The reason I'm opening this ticket is to ask: has anyone else figured out how to make QueryFactory performant in all situations? Developer orgs shouldn't behave differently than production deployed packaged code.

**Comment by capeterson** [comment]
Can you share the case number (don't need the contents, but if we talk to salesforce R&D want to be able to reference it). One big thing we found on a recent internal investigation was the amount of time spent sorting fields to get consistent SOQL output is really a killer. It's looking like having deterministic field ordering should be optional (and really, default to off) for the sake of performance - only used when needing to compare the result against a known good value.

Seeing as queryfactory is getting a major uptake in use I can reach out to a couple people on the apex team and see if they have any advice as well - wasting CPU time is just as bad for the platform as it is for us.

**Comment by daveespo** [comment]
Heh, "fun" would've been my first characterization too :-)

It's Case #12348492 and it's still open -- I'll post any interesting updates if they come along

Interesting about the sorting of the field list -- I'm holding out hope that the [Platform Cache](https://developer.salesforce.com/blogs/engineering/2015/05/platform-cache.html) is going to buy a lot of performance happiness for situations like this

**Comment by capeterson** [comment]
It might, but the use cases are limited since queryfactory is designed to be used with very dynamic queries. We could look into caching results in the per-user platform cache, but how much that's going to help is up in the air. I'd personally rather go beat up salesforce (and ourselves) to get it runtime optimized as much as possible.

**Comment by daveespo** [comment]
I have one Known Issue I've gotten filed thus far:

https://success.salesforce.com/issues_view?id=a1p30000000eMoeAAE

This came out of them claiming that we could just solve this lack of call to hashCode() by setting the log filters accordingly. Three weeks later and we have proven that this is not an adequate workaround given that log filter overrides are their own bug farm.

**Comment by daveespo** [comment]
At this point, I guess it's time to close out this issue -- The Case with Support has run its course and ended up back where it was when I first opened this issue -- basically stating verbatim the same business about how the log level of "FINEST" causes the underlying implementation of Map/Set to change and disregard the hashCode() implemented in the user class.

Ultimately, this behavior coupled with the bug enumerated in the Known Issue above means that we need to remove any log filter overrides and ensure that we have our user log level set to DEBUG before making any measurements around performance of transactions

For the record, the first case got split into two cases -- the other one is 12550769

**Comment by afawcett** [comment]
@agarciaodeian have we shared the performance improvements we made to QueryFactory here yet? cc @capeterson
