### ISSUE TITLE
Create Domain Class from non-concrete list of SObjects

### ISSUE THREAD

**Issue by jondavis9898** [financialforcedev/fflib-apex-common#82]
Currently a concrete list of SObjects is required in order to create an instance of an fflib_SObjectDomain class.  The reason for this is that the constructor of fflib_SObjectDomain calls [getSObjectType()](https://github.com/financialforcedev/fflib-apex-common/blob/master/fflib/src/classes/fflib_SObjectDomain.cls#L91) on the list specified in the constructor arguments and this call will return null if the List is not of a concrete type (e.g. Opportunity, Account, etc.).

Use Case: In an approach similar to what fflib UOW does, I have a need to keep a Map of SObjects by type and then iterate the map, constructing a domain class and invoking methods on it (methods are exposed via common interface).  Currently, my only solution is to keep a static map of concrete Lists to SObjectTypes which can be cloned and used within an execution context.  This carries with it additional maintenance/support overhead in managing an "Application" class as well as the perf cost incurred cloning large maps (we have 100+ domain classes).  An alternate solution would be to add a constructor to fflib_SObjectDomain allowing the SObjectType to be supplied instead of inferred from the List supplied. 

Unfortunately, there is no way to create an List of a specific SObjectType at runtime.  Given the goal of SObjectDomain classes and ability to use them outside of a trigger context (which supplies concrete lists in Trigger Maps), adding the constructor seems to make sense and provide a mechanism to do.

Interested in any feedback and especially for those more familiar with the entire fflib package, if not having a concrete list of "Records" could present any downstream impacts.

**Comment by afawcett** [comment]
Thanks for the PR! :+1:  Merged.

**Comment by jondavis9898** [comment]
tag this as enhancement for tracking purposes?

**Comment by afawcett** [comment]
Done. :+1:
