### ISSUE TITLE
System.CalloutException: You have already created Savepoints. You cannot make callout after creating a Savepoint

### ISSUE THREAD

**Issue by thegogz** [financialforcedev/fflib-apex-common#90]
I'm currently working on implementing this library for our organization and am struggling with an issue in unit tests

```
System.CalloutException: You have already created Savepoints.   You cannot make callout after creating a Savepoint
```

What I did was extend the ```fflib_SobjectUnitOfWork``` class using a custom class with an additional "Work" item inner-class SendSMSWork which calls my SMS integration class. This follows the same pattern as the registerEmail pattern already in the parent class. When I originally tried this in the UI all works absolutely fine and my SMS is sent. However in my Unit tests I'm having issues with the above error. 

I'm wondering if anyone else has solved this issue and what would be the advised way within the context of this library?

I'm hoping I can mock out my SMS Service which would allow these tests to pass.

**Comment by tfuda** [comment]
Is the callout to your SMS integration class via an @future method call? If so, are you using System.startTest and System.stopTest calls around this method call to make it run as a synchronous operation? I think that would cause the callout to be part of the same transaction in which you've created the savepoint.

**Comment by thegogz** [comment]
Thanks @tfuda that has helped work around the issue. The call is indeed in an *@future* For now I can just watch where I use the Test.stopTest() and Test.startTest() in my tests.
