### ISSUE TITLE
addQueryFactorySubselect deprecated method for sObject (Related)

### ISSUE THREAD

**Issue by phyopine-gscs** [financialforcedev/fflib-apex-common#92]
Since subselectQuery(SObjectType related) method is deprecated in fflib_QueryFactory, are there any changes in the works for addQueryFactorySubselect method in fflib_SObjectSelector class?

I am assuming there should be method overload with  passing relationship name instead of related sObject from selector.

**Comment by afawcett** [comment]
Not sure what it is your asking for here. A configured Query Factory is exposed from fflib_SObjectSelector via the newQueryFactory method, at this point you can call whatever methods you desire before calling toSOQL. Does this help?

**Comment by phyopine-gscs** [comment]
@afawcett , what I meant is in fflib_SObjectSelector addQueryFactorySubselect method is calling subSelectQuery(SObjectType related) method on line 330 of fflib_ObjectSelector.cls 

Doesn't that call need to be updated since that method is deprecated in fflib_QueryFactory?

But I guess you are right, I can just get the configured Query Factory via newQueryFactory() method from Selector and call the methods from QueryFactory themselves.

**Comment by phyopine-gscs** [comment]
@afawcett  So, to continue on what I was saying before, on very hack-ish way I can add public method like that in fflib_SObjectSelector. 

```
  public fflib_QueryFactory addQueryFactorySubselect(fflib_QueryFactory parentQueryFactory, Boolean includeSelectorFields, String relationshipName)
    {       
        fflib_QueryFactory subSelectQueryFactory = 
            parentQueryFactory.subselectQuery(relationshipName);
        return configureQueryFactory(
            subSelectQueryFactory, 
            m_enforceCRUD, 
            m_enforceFLS, 
            includeSelectorFields);
    }
```

To use your sample example, following method call will become
```
public List<Opportunity> selectByIdWithProducts(Set<ID> idSet)
	{
		fflib_QueryFactory opportunitiesQueryFactory = newQueryFactory();

		fflib_QueryFactory lineItemsQueryFactory = 
			new OpportunityLineItemsSelector().
				addQueryFactorySubselect(opportunitiesQueryFactory);

```

something like this after the changes...

```
public List<Opportunity> selectByIdWithProducts(Set<ID> idSet)
	{
		fflib_QueryFactory opportunitiesQueryFactory = newQueryFactory();

		fflib_QueryFactory lineItemsQueryFactory = 
			new OpportunityLineItemsSelector().
				addQueryFactorySubselect(opportunitiesQueryFactory,true,'OpportunityLineItems');

```
Thoughts?

**Comment by afawcett** [comment]
Sorry for the delay, yes that looks great. Can you do a PR?

**Comment by phyopine-gscs** [comment]
Hi @afawcett , sure thing. Will do that. 

Happy Holidays!

**Comment by afawcett** [comment]
:+1:
