### ISSUE TITLE
EnforcingTriggerCRUDSecurity=true is not backwards compatible for triggers

### ISSUE THREAD

**Issue by jmrjulian** [financialforcedev/fflib-apex-common#94]
The default instantiation of `Configuration` in the Domain class is as follows:

```java
public Configuration()
{
	EnforcingTriggerCRUDSecurity = true; // Default is true for backwards compatability
	...
}
```

Contrary to the what the comment say, the default behaviour of Salesforce triggers is to run in system context without enforcing CRUD security. For example, the following trigger will create an invoice record even if the running user does not have the permission to do so:

```java
trigger AccountsTrigger on Account (after insert) {
	insert new Invoice__c(Description__c = 'trigger created');
}
```

In effect, the after-event handler methods of the Domain class  (`handleAfterInsert()`, `handleAfterUpdate()`, etc.) imposes a different behaviour than SFDC's default.

```java
if(Configuration.EnforcingTriggerCRUDSecurity && !SObjectDescribe.isUpdateable()) 			    		
    throw new DomainException('Permission to udpate an ' + SObjectDescribe.getName() + ' denied.');
```

**Comment by afawcett** [comment]
Hi, yes, the comment actually refers to the default behaviour of this library reflecting its historic hard coded behaviour prior to adding this config. So is setting was not ever intended to reflect the platforms standard behaviour. If you want the default to reflect the platform create your own base class and extend that in your domain objects, e.g.

    public class MyDomainClass extends fflib_SObjectDomain {
       public MyDomainClass(List<SObject> records) {
          super(records);
          Configuration. disableTriggerCRUDSecurity();
       }
    }

    public class Accounts extends MyDomainClass {
      public Accounts(List<SObject> records) {
         super(records);
      }
    }

**Comment by jmrjulian** [comment]
Thanks!
