### ISSUE TITLE
fflib_Application.UnitOfWork Support for fflib_SObjectUnitOfWork.IDML

### ISSUE THREAD

**Issue by daniel-huckins** [financialforcedev/fflib-apex-common#96]
**feature request**
Would it be possible to add an option to pass in a fflib_SObjectUnitOfWork.IDML into the fflib_Application.UnitOfWork inner class?
Can't think of a reason against it but wanted to ask before working on a pull request.

thanks!

**Comment by afawcett** [comment]
Sounds reasonable. I've flagged this as an enhancement, can you share a snippet as an example to be clear i understand what you mean?

**Comment by daniel-huckins** [comment]
Sure;
In this case the org has some form data comming in from external sources, while having some fairly complex duplicate matching rules.
The requirements were to allow all form submissions to go through, bypassing the duplicate rules, and then they will handle the possible duplicates after the fact.
This can be done by using the ```Database.DMLOptions.DuplicateRuleHeader``` ([docs]) and passing a new fflib_SObjectUnitOfWork.IDML to the uow.

```apex
public class MyDML implements fflib_SObjectUnitOfWork.IDML
{
  private Database.DMLOptions dmlOptions;

  public MyDML()
  {
    dmlOptions = new Database.DMLOptions();
    dmlOptions.DuplicateRuleHeader.allowSave = true;
  }

  public void dmlInsert(List<SObject> objList)
  {
    Database.insert(objList, dmlOptions);
  }

  public void dmlUpdate(List<SObject> objList)
  {
    Database.update(objList, dmlOptions);
  }

  public void dmlDelete(List<SObject> objList)
  {
    delete objList;
  }
}
```

Right now, ```MyDML``` can be passed in to construct a new uow, but is not a parameter in  ```fflib_Application.UnitOfWorkFactory```

Should it even be an option?
Let me know what you think.

thanks!


[docs]: <https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_class_Database_DMLOptions_DuplicateRuleHeader.htm#apex_class_Database_DMLOptions_DuplicateRuleHeader>

**Comment by afawcett** [comment]
Maybe an overload to the fflib_Application.UnitOfWorkFactory constructor so you can do...

	public static final fflib_Application.UnitOfWorkFactory UnitOfWork = 
		new fflib_Application.UnitOfWorkFactory(
				new List<SObjectType> { 
					Invoice__c.SObjectType,
					InvoiceLine__c.SObjectType,
					Opportunity.SObjectType,
					Product2.SObjectType,
					PricebookEntry.SObjectType,
					OpportunityLineItem.SObjectType },
				new MyDML());	

Then when you use the factory it creates a new instance with the DML impl given...

    fflib_IUnitOfWork uow = Application.UnitOfWork.newInstance();

This would ensure its always applied across your app.

The other thought if its uow instance specific....

    fflib_IUnitOfWork uow = Application.UnitOfWork.newInstance(new MyDML());

**Comment by daniel-huckins** [comment]
Requesting to close this issue with some words of warning to anyone trying the same (or at least bring up a possible discussion point).
Using ```Database.DMLOptions.DuplicateRuleHeader.allowSave``` will indeed let you save over duplicate rules in place; however, if the record fails a validation rule it will <b>fail silently</b>

Example: There is a validation rule on Account, that throws an error when 'Fail_Me__c' = true.
```apex
Database.DMLOptions dmlOptions = new Database.DMLOptions();
dmlOptions.DuplicateRuleHeader.allowSave = true;
List<SObject> toInsert = new List<SObject>();

Account iPass = new Account();
iPass.Name = 'I Pass validation';
iPass.Fail_Me__c = false;
toInsert.add(iPass);

Account iFail = new Account();
iFail.Name = 'I Fail validation';
iFail.Fail_Me__c = true; // should get an error
toInsert.add(iFail);

Database.insert(toInsert, dmlOptions);

/*shouldn't get here but we do*/
System.debug('*** iPass.Id: ' + iPass.Id);
System.debug('*** iFail.Id: ' + iFail.Id);
```
Completes successfully, no errors, with a result of:
```
USER_DEBUG|[15]|ERROR|*** iPass.Id: 00136000002X7U5AAK
USER_DEBUG|[17]|ERROR|*** iFail.Id: null
```

Maybe I'm not using it correctly, but something seems off here right?

**Comment by afawcett** [comment]
Yeah for sure, have you tried passing this through Salesforce SUpport?

**Comment by daniel-huckins** [comment]
Yes, long story short, there was no solution offered. 
Due to the strict deadline on the project we discarded the requirement (at the expense of the users unfortunately) 
Just posted the problem on [stackexchange](http://salesforce.stackexchange.com/questions/105233/database-dmloptions-duplicateruleheader-allowsave-skips-all-validation-rules).
Thanks for your support @afawcett

**Comment by tfuda** [comment]
@daniel-huckins What if you specify dmlOptions.optAllOrNone = true? By default, that option is false. And you then have to check the Database.SaveResult object to determine which, if any of your records has errors.

**Comment by cropredyHelix** [comment]
One would think the solution would be to simply `setdmlOptions` on the registered sobject as the [Apex documentation](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_dml_database_dmloptions.htm) says should be possible. However, [Known Issue](https://trailblazer.salesforce.com/issues_view?id=a1p4V000001vCw8QAE) prevents this. See also [stackexchange post on issue ](https://salesforce.stackexchange.com/questions/374271/inconsistent-behavior-of-setting-dmloptions-duplicateruleheader)(motivated by trying to use registerDirty on an sobject with dmlOptions applied via setDmlOptions)

**Comment by ImJohnMDaniel** [comment]
G'day @KalpeshChande.  Is your question "how would you access the IDML implementation that was passed to the UOW?" or "If you are using the fflib_Application.UnitOfWorkFactory, how do you pass a custom IDML?"

**Comment by cropredyHelix** [comment]
The class that implements IDML has public methods but why would you want to call those directly from some other class? They are intended to be called from the UnitOfWork object as an alternate implementation of the OOTB SimpleDml inner class
